(defun catppuccin-colors ()
  (write-region (concat (char-to-string 27) "]P" "0" "1e1e2e" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "8" "45475a" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "1" "f38ba8" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "9" "eba0ac" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "2" "a6e3a1" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "A" "a6e3a1" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "3" "fab387" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "B" "f9e2af" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "4" "89b4f4" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "C" "74c7ec" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "5" "cba6f7" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "D" "b4befe" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "6" "89dceb" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "E" "94e2d5" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "7" "cdd6f4" "\n") nil "/dev/console" t)
  (write-region (concat (char-to-string 27) "]P" "F" "9399b2" "\n") nil "/dev/console" t)
  t)

(provide 'catppuccin)
